<!DOCTYPE html>
<html><head><title>joekychen/django » django › contrib › gis › geos › error.py

</title>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
<meta name="generator" content="Docco">
<link rel="stylesheet" media="all" href="../../../../stylesheets/docco.min.css" />


</head>
<body>
<div id="container">
<div id="background"></div>
<table cellpadding="0" cellspacing="0">
<thead><tr><th class="docs"><a id="home" href="../../../../index.html"></a><h1>error.py</h1></th><th class="code"></th></tr></thead>
<tbody>


<tr id="section-1"><td class="docs"><div class="pilwrap"><a class="pilcrow" href="#section-1">&#182;</a></div></td><td class="code"><div class="highlight"><pre><span class="sd">&quot;&quot;&quot;</span>
<span class="sd"> This module houses the GEOS exceptions, specifically, GEOSException and</span>
<span class="sd"> GEOSGeometryIndexError.</span>
<span class="sd">&quot;&quot;&quot;</span>

<span class="k">class</span> <span class="nc">GEOSException</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
    <span class="s">&quot;The base GEOS exception, indicates a GEOS-related error.&quot;</span>
    <span class="k">pass</span>

<span class="k">class</span> <span class="nc">GEOSIndexError</span><span class="p">(</span><span class="n">GEOSException</span><span class="p">,</span> <span class="ne">KeyError</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;</span>
<span class="sd">    This exception is raised when an invalid index is encountered, and has</span>
<span class="sd">    the &#39;silent_variable_feature&#39; attribute set to true.  This ensures that</span>
<span class="sd">    django&#39;s templates proceed to use the next lookup type gracefully when</span>
<span class="sd">    an Exception is raised.  Fixes ticket #4740.</span>
<span class="sd">    &quot;&quot;&quot;</span></pre></div></td></tr>


<tr id="section-2"><td class="docs"><div class="pilwrap"><a class="pilcrow" href="#section-2">&#182;</a></div><p>"If, during the method lookup, a method raises an exception, the exception
 will be propagated, unless the exception has an attribute 
 <code>silent_variable_failure</code> whose value is True." -- Django template docs.</p></td><td class="code"><div class="highlight"><pre>    <span class="n">silent_variable_failure</span> <span class="o">=</span> <span class="bp">True</span>

</pre></div></td></tr>

</tbody>
</table>
</div>

</body>
<script>docas={repo:"joekychen/django",depth:4}</script>
<script>document.write('<script src=' + ('__proto__' in {} ? 'http://cdnjs.cloudflare.com/ajax/libs/zepto/1.0rc1/zepto.min.js' : 'https://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js')+'><\\/script>')</script>
<script src="http://baoshan.github.com/moment/min/moment.min.js"></script>
<script src="../../../../javascript/docco.min.js"></script>
</html>
